SELECT ENAME, COMM+300 보너스 FROM EMP;
--문자열 합성 연산자
DESC EMP
DESC DEPT
-- 1. 문자열과 문자열 합성
SELECT ENAME||JOB FROM EMP; 
-- 2. 문자열과 문자열을 합성해서 새로운 칼럼으로 생성 
SELECT DNAME||'부서는'||LOC||'지역에 위치합니다.'as LOC FROM DEPT;
-- 3. 숫자와 문자 결합 
SELECT ENAME, SAL, SAL*100, SAL||'00', to_char(SAL)||'00' FROM EMP;

-- DUAL
DESC dual
SELECT * FROM DUAL;
SELECT 143475*127363, TO_CHAR(143475*127363, '999,999,999,999') FROM DUAL;

-- WHERE
SELECT * FROM EMP WHERE DEPTNO = 10;
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE SAL > 2000;
DESC EMP;
SELECT SALGRADE, SAL, EMPNO, ENAME FROM EMP WHERE DEPTNO = 10 AND SAL > 2000;
SELECT DEPTNO, SAL, EMPNO, ENAME FROM EMP WHERE DEPTNO = 10 AND SAL > 2000;
SELECT DEPTNO, SAL, EMPNO, ENAME FROM EMP WHERE DEPTNO = 10 OR SAL > 2000;
SELECT * FROM EMP;
SELECT DEPTNO, ENAME, JOB FROM EMP WHERE JOB = 'MANAGER';
SELECT DEPTNO, ENAME, JOB FROM EMP WHERE 1 = 1;
SELECT DEPTNO, ENAME, JOB FROM EMP WHERE 1 = 2;

-- ORDER BY
SELECT DEPTNO, ENAME, SAL, HIREDATE FROM EMP ORDER BY ENAME;
SELECT DEPTNO, ENAME, SAL, HIREDATE FROM EMP ORDER BY SAL;
SELECT DEPTNO, ENAME, SAL, HIREDATE FROM EMP ORDER BY SAL ASC;
SELECT DEPTNO, ENAME, SAL, HIREDATE FROM EMP ORDER BY SAL DESC;
SELECT DEPTNO, JOB, ENAME FROM EMP ORDER BY DEPTNO;
SELECT DEPTNO, JOB, ENAME FROM EMP ORDER BY DEPTNO, JOB;
SELECT DEPTNO, JOB, ENAME FROM EMP ORDER BY DEPTNO, JOB DESC;

SELECT * FROM EMP ORDER BY HIREDATE DESC;

-- DISTINCT, FUNCTION
SELECT JOB FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT DISTINCT DEPTNO, JOB FROM EMP;
SELECT DISTINCT DEPTNO, JOB FROM EMP ORDER BY DEPTNO;
SELECT DISTINCT DEPTNO, DISTINCT JOB FROM EMP;
SELECT DEPTNO, DISTINCT JOB FROM EMP;

SELECT ENAME, LENGTH(ENAME), UPPER(ENAME), LOWER(ENAME) FROM EMP;
SELECT COUNT(*), COUNT(SAL), AVG(SAL), MIN(SAL), MAX(SAL) FROM EMP;

SELECT DISTINCT * FROM EMP;
SELECT * FROM EMP;