-- ���� 4
    -- CASE Ȱ��
SELECT DEPTNO, ENAME, JOB, SAL, 
    CASE DEPTNO WHEN 10 THEN TRUNC(SAL * 0.003)
                WHEN 20 THEN TRUNC(SAL * 0.2)
                WHEN 30 THEN TRUNC(SAL * 0.1)
                ELSE TRUNC(SAL * 0.01)
    END AS BONUS
FROM EMP ORDER BY DEPTNO ASC,BONUS DESC;

    -- DECODE
SELECT DEPTNO, ENAME, JOB, SAL,
DECODE (DEPTNO, 10, SAL*1.003, 20. SAL*1.2, 30, SAL*1.1, SAL*1.01) AS BONUS
FROM EMP
ORDER BY DEPTNO ASC, BONUS DESC;

-- ���� 5
    -- ROWNUM, ORDER BY, SUBQUERY�� �����ؼ� TOP-N, BOTTOM-M�� �̴� SQL �ۼ�
  
SELECT ENAME, SAL
FROM ( SELECT ENAME, SAL 
       FROM EMP
       ORDER BY SAL DESC )
WHERE ROWNUM <= 5;

-- ���� 2
    -- union, union all, intersect, minius�� ������ �� ������ ���� sql���� ������ ����� �� ���ĵǴ��� �����Ͻÿ�. 
    SELECT * FROM DEPT;
    SELECT * FROM EMP;
    
    -- UNION
    SELECT DEPTNO FROM EMP
    UNION
    SELECT DEPTNO FROM DEPT;
    
    -- UNION ALL
    SELECT DEPTNO FROM EMP
    UNION ALL
    SELECT DEPTNO FROM DEPT;
    
    -- INTERSECT
    SELECT DEPTNO FROM EMP
    INTERSECT
    SELECT DEPTNO FROM DEPT;
    
    -- MINUS
    SELECT DEPTNO FROM EMP
    MINUS
    SELECT DEPTNO FROM DEPT;
    
    SELECT DEPTNO FROM DEPT
    MINUS
    SELECT DEPTNO FROM EMP;

-- DUAL
SELECT SYSDATE FROM DUAL;
SELECT * FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'HH:MI:SS') FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
-- ����
SELECT TO_CHAR(SYSDATE, 'HH:MI:SS'), TO_CHAR(SYSTIMESTAMP, 'FF2') FROM DUAL;
SELECT TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD HH24:MI:SS.FF2') as TIME FROM DUAL;

-- NULL
SELECT 300+400, 300/0 FROM DUAL;
SELECT 300+400, 300+NULL, 300/NULL FROM DUAL;
SELECT ENAME, SAL, COMM, COMM+SAL*0.3 AS BONUS FROM EMP;

SELECT EMPNO, SAL, COMM FROM EMP;
SELECT ENAME, SAL, COMM FROM EMP WHERE SAL > 1000;
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM > -1;
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM = NULL;
SELECT ENAME, SAL, COMM, FROM EMP WHERE COMM <> NULL;

SELECT ENAME, SAL, COMM FROM EMP WHERE COMM IS NULL;
SELECT ENAME, SAL, COMM FROM EMP WHERE COMM IS NOT NULL;

SELECT ENAME, LENGTH(ENAME), COMM, LENGTH(COMM) FROM EMP;
SELECT SAL-EMPNO, ABS(SAL-EMPNO), ABS(SAL-COMM)+100 FROM EMP;

SELECT COUNT(*), COUNT(COMM), SUM(COMM), AVG(COMM) FROM EMP;
SELECT ENAME, SAL, COMM, NVL(COMM, 0) + SAL * 0.3 AS BONUS FROM EMP;

SELECT COUNT(*) FROM SCOTT.EMP;
SELECT COUNT(*) FROM SCOTT.EMP WHERE 1 = 1;
SELECT COUNT(*) FROM SCOTT.EMP WHERE EMPNO = EMPNO;
SELECT COUNT(*) FROM SCOTT.EMP WHERE MGR = MGR;
SELECT COUNT(*) FROM SCOTT.EMP WHERE COMM = COMM;

DESCRIBE EMP;

-- ORDER BY
SELECT ENAME, HIREDATE FROM EMP;
SELECT ENAME, HIREDATE FROM EMP ORDER BY ENAME;
SELECT ENAME, HIREDATE FROM EMP ORDER BY ENAME ASC;
SELECT ENAME, HIREDATE FROM EMP ORDER BY ENAME DESC;

SELECT ENAME, SAL, HIREDATE FROM EMP ORDER BY ENAME;
SELECT ENAME, SAL, HIREDATE FROM EMP ORDER BY 1;
SELECT ENAME, SAL*12 AS ANNUAL_SAL FROM EMP ORDER BY ANNUAL_SAL;
SELECT EMPNO, ENAME, COMM, JOB FROM EMP ORDER BY COMM*12;

SELECT DEPTNO, JOB, ENAME FROM EMP ORDER BY DEPTNO;
SELECT DEPTNO, JOB, ENAME FROM EMP ORDER BY DEPTNO, JOB;
SELECT DEPTNO, JOB, ENAME FROM EMP ORDER BY DEPTNO, JOB DESC;

SELECT ENAME, HIREDATE FROM EMP ORDER BY SAL DESC;

SELECT EMPNO, COMM FROM EMP ORDER BY COMM ASC;
SELECT EMPNO, COMM FROM EMP ORDER BY COMM DESC;

-- DISTINCT
SELECT COUNT(DISTINCT COMM) FROM EMP;

-- DECODE, CASE
SELECT DEPTNO,ENAME,SAL,COMM,
CASE WHEN COMM >= 5000 THEN 'HIGH'
	 WHEN COMM >= 2500 THEN 'MID'
	 WHEN COMM BETWEEN 300 AND 2500 THEN 'LOW'
ELSE
	'UNKNOWN'
END
FROM EMP ORDER BY DEPTNO;

SELECT GREATEST(3000,1500,2100,5000),LEAST(3000,1500,2100,5000)FROM DUAL;

SELECT DEPTNO,ENAME,SAL,
       DECODE(GREATEST(SAL,5000),SAL,'HIGH',
       DECODE(GREATEST(SAL,2500),SAL,'MID','LOW'))
FROM EMP
ORDER BY DEPTNO;


SELECT SAL, 
	CASE WHEN SAL >= 1000 THEN 1 
			 WHEN SAL >= 2000 THEN 2
			 WHEN SAL >= 3000 THEN 3
			 WHEN SAL >= 4000 THEN 4
			 WHEN SAL >= 5000 THEN 5
			 ELSE 0 
			 END AS SAL_CHK 
FROM EMP ORDER BY SAL;

SELECT SAL, 
	CASE WHEN SAL >= 1000 THEN 1 
			 WHEN SAL >= 2000 THEN 2
			 WHEN SAL >= 3000 THEN 3
			 WHEN SAL >= 4000 THEN 4
			 WHEN SAL >= 5000 THEN 5
			 ELSE 0 
			 END AS SAL_CHK 
FROM EMP ORDER BY SAL;

SELECT SAL, 
	CASE WHEN SAL >= 5000 THEN 5 
			 WHEN SAL >= 4000 THEN 4
			 WHEN SAL >= 3000 THEN 3
			 WHEN SAL >= 2000 THEN 2
			 WHEN SAL >= 1000 THEN 1
			 ELSE 0 
			 END AS SAL_CHK 
FROM EMP ORDER BY SAL;


SELECT DEPTNO, SAL FROM EMP;



SELECT DEPTNO,ENAME,JOB,SAL,
TRUNC(DECODE(DEPTNO,10,SAL*0.003,20,SAL*0.2, 30, SAL*0.1, SAL*0.01)) AS BONUS 
FROM EMP ORDER BY DEPTNO ASC,BONUS DESC;

-- ROWNUM
SELECT ROWNUM, ENAME, DEPTNO, SAL FROM EMP;
SELECT ROWNUM, ENAME, DEPTNO, SAL FROM EMP ORDER BY DEPTNO, SAL;

SELECT ROWNUM, ENAME, DEPTNO, SAL FROM EMP WHERE DEPTNO IN (10, 20) ORDER BY DEPTNO, SAL;

SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM = 1;
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM = 5;
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM > 5;
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM <= 5;
SELECT ENAME, DEPTNO, SAL FROM EMP WHERE ROWNUM < 1;

SELECT DEPTNO, ENAME, SAL
FROM EMP
ORDER BY SAL DESC;

-- ��������
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP WHERE SAL > 2000 OR SAL > 2000;
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP WHERE SAL > 1000 OR SAL > 2000;
SELECT ENAME, JOB, SAL, DEPTNO FROM EMP
WHERE DEPTNO = 10 AND SAL > 2000 OR JOB = 'CLERK';
SELECT DEPTNO, ENAME, JOB, SAL FROM EMP WHERE SAL > 2000 OR JOB = 'CLERK' AND DEPTNO >= 20;
SELECT ENAME, JOB, SAL FROM EMP WHERE SAL > 2000 OR (JOB = 'CLERK' AND DEPTNO >= 20);
SELECT ENAME,JOB,SAL,DEPTNO FROM EMP
WHERE (DEPTNO = 10 AND SAL > 2000) OR JOB = 'CLERK';  
SELECT ENAME,JOB,SAL,DEPTNO FROM EMP 
WHERE DEPTNO = 10 AND    (SAL > 2000 OR JOB = 'CLERK');
SELECT ENAME,JOB,SAL FROM EMP WHERE JOB != 'CLERK';
SELECT ENAME,JOB,SAL FROM EMP WHERE JOB NOT IN('CLERK','MANAGER');
SELECT ENAME,JOB,SAL FROM EMP WHERE SAL > 2000 OR JOB = 'CLERK';
SELECT ENAME,JOB,SAL FROM EMP WHERE SAL> 2000 AND JOB = 'CLERK';

-- BETWEEN
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL BETWEEN 1000 AND 2000;
SELECT EMPNO,ENAME,SAL FROM EMP WHERE SAL >= 1000 and SAL <= 2000;
SELECT EMPNO,ENAME,HIREDATE,SAL FROM EMP WHERE SAL between 2000 and 1000;
SELECT EMPNO,ENAME,HIREDATE,SAL FROM EMP WHERE ENAME between 'C' and 'K';
SELECT EMPNO,HIREDATE,SAL FROM EMP WHERE HIREDATE between '81/02/20' and '82/12/09';
SELECT ENAME,HIREDATE,SAL FROM EMP WHERE HIREDATE between to_date('81/02/20','yy/mm/dd') and to_date('82/12/09','yy/mm/dd');// ?
SELECT ENAME,HIREDATE,SAL FROM EMP WHERE HIREDATE between to_date('81/02/20','rr/mm/dd') and to_date('81/12/09','rr/mm/dd');

SELECT TO_DATE('50.01', 'yy.mm') -- 2050
    , TO_DATE('50.01', 'rr.mm') -- 1950
    , TO_DATE('99.01', 'yy.mm') -- 2099
    , TO_DATE('99.01', 'rr.mm') -- 1999
    FROM DUAL;
    
SELECT * FROM SALGRADE WHERE 3000 BETWEEN LOSAL AND HISAL;

-- IN
SELECT EMPNO,ENAME,JOB FROM EMP WHERE EMPNO IN(7369,7521,7654);
SELECT EMPNO,ENAME,JOB FROM EMP WHERE EMPNO = 7369 or EMPNO = 7521 or EMPNO=7654;
SELECT EMPNO,ENAME,JOB FROM EMP WHERE JOB in ('clerk','manager');
SELECT EMPNO,ENAME,HIREDATE FROM EMP WHERE HIREDATE IN('81/05/01','81/02/20');
SELECT EMPNO,ENAME,JOB,DEPTNO FROM EMP 
WHERE(JOB,DEPTNO) in (('MANAGER',20),('CLERK',20));
SELECT EMPNO,ENAME,JOB FROM EMP WHERE EMPNO IN (7369,7369,7654);

-- like
SELECT ENAME FROM EMP WHERE ENAME like 'A%';
SELECT ENAME FROM EMP WHERE ENAME like '_A%';
SELECT ENAME FROM EMP WHERE ENAME like '%L%E%';
SELECT ENAME FROM EMP WHERE ENAME like '%LE%';
SELECT ENAME FROM EMP WHERE ENAME like '%A%';
SELECT ENAME FROM EMP WHERE ENAME NOT like '%A%';
SELECT ENAME,HIREDATE FROM EMP WHERE HIREDATE like '81%';
SELECT ENAME,SAL FROM EMP WHERE SAL like 2%;
SELECT ENAME,SAL FROM EMP WHERE SAL like '2%';
SELECT EMPNO, ENAME FROM EMP WHERE EMPNO = '7369';


-- 과제 0508
SELECT DECODE (TO_CHAR(LAST_DAY(SYSDATE), 'D'), 7, LAST_DAY(SYSDATE) -1,
                                                1, LAST_DAY(SYSDATE) -2,
                                                LAST_DAY(SYSDATE))
                                                AS "LAST BUSINESS DAY OF THE MONTH"
FROM DUAL;
