-- 과제 3번
    -- 까막
SELECT A.DEPTNO AS 부서번호, A.ENAME AS 이름, A.JOB AS 직업, A.SAL AS 급여,
COUNT(DISTINCT B.SAL) AS "급여순위"
FROM EMP A, EMP B 
WHERE A.DEPTNO = B.DEPTNO
AND
A.SAL <= B.SAL 
GROUP BY A.DEPTNO, A.ENAME, A.JOB, A.SAL
ORDER BY A.DEPTNO ASC, A.SAL DESC;
    -- 나
SELECT  A.DEPTNO AS 부서번호, A.ENAME AS 이름, A.JOB AS 직업, A.SAL AS 급여, COUNT(B.ENAME)+1 AS 급여수준
FROM EMP A, EMP B
WHERE A.SAL < B.SAL(+) 
AND A.DEPTNO = B.DEPTNO(+)
GROUP BY A.DEPTNO, A.ENAME, A.JOB, A.SAL
ORDER BY A.ENAME, A.DEPTNO, A.SAL DESC;

SELECT  A.DEPTNO AS 부서번호, A.ENAME AS 이름, A.JOB AS 직업, A.SAL AS 급여
FROM EMP A, EMP B
WHERE A.SAL < B.SAL(+) 
AND A.DEPTNO = B.DEPTNO(+)
--GROUP BY A.DEPTNO, A.ENAME, A.JOB, A.SAL
ORDER BY A.ENAME, A.DEPTNO, A.SAL DESC;

-- 과제 4번
    -- RANK()
SELECT DEPTNO AS 부서번호, ENAME AS 이름, JOB AS 직업, SAL AS 급여, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS "급여순위"
FROM EMP 
GROUP BY DEPTNO, JOB, ENAME, SAL;

    -- DENSE_RANK()
SELECT DEPTNO AS 부서번호, ENAME AS 이름, JOB AS 직업, SAL AS 급여, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS "급여순위"
FROM EMP 
GROUP BY DEPTNO, JOB, ENAME, SAL;

-- 과제 5번
SELECT DEPTNO, EMPNO, ENAME, SAL, TRUNC(SAL/SUM_SAL*100, 2) AS SAL_RATE
FROM EMP, (SELECT SUM(SAL) AS SUM_SAL FROM EMP);

SELECT*FROM EMP;


SELECT*FROM V$MYSTAT;