-- °úÁ¦
SELECT DEPTNO, ENAME, JOB, SAL 
FROM EMP
ORDER BY DEPTNO;

-- EQUI-JOIN
SELECT * FROM EMP;

SELECT DNAME, ENAME, JOB, SAL 
FROM EMP, DEPT
WHERE DEPTNO = DEPTNO;

SELECT DNAME,ENAME,JOB,SAL 
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT DNAME,ENAME,JOB,SAL
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.JOB IN ('MANAGER','CLERK')
ORDER BY DNAME;

SELECT DEPT.DNAME,EMP.ENAME,EMP.JOB,EMP.SAL 
FROM SCOTT.EMP,SCOTT.DEPT 
WHERE    EMP.DEPTNO = DEPT.DEPTNO;

SELECT D.DNAME,E.ENAME,E.JOB,E.SAL 
FROM EMP E,DEPT D
WHERE    E.DEPTNO = D.DEPTNO;

SELECT D.DNAME,E.ENAME,E.JOB,E.SAL 
FROM      EMP E INNER JOIN DEPT D   ON   E.DEPTNO = D.DEPTNO;

SELECT D.DNAME,E.ENAME,E.JOB,E.SAL 
FROM   EMP E INNER JOIN DEPT D   ON       E.DEPTNO = D.DEPTNO
WHERE   E.DEPTNO IN (10,20) AND D.DNAME = 'RESEARCH';

-- NON-EQUI-JOIN
SELECT  E.ENAME, E.JOB,E.SAL,S.GRADE
FROM    EMP E,SALGRADE S
WHERE   E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT 	DNAME,ENAME,JOB,SAL,GRADE 
FROM 	EMP E, DEPT D, SALGRADE S 
WHERE   E.DEPTNO = D.DEPTNO AND E.SAL BETWEEN S.LOSAL AND S.HISAL; 

SELECT 	E.ENAME, E.JOB,E.SAL,S.GRADE 
FROM    EMP E, SALGRADE S
WHERE 	E.SAL BETWEEN S.LOSAL AND S.HISAL AND E.DEPTNO IN (10,30)
ORDER   BY E.ENAME;

SELECT      E.ENAME, E.JOB,E.SAL,S.GRADE    
FROM    	EMP E, SALGRADE S
WHERE      	E.SAL    <    S.LOSAL AND E.DEPTNO IN (10,30)
ORDER	 	BY E.ENAME;

SELECT * FROM SALGRADE;

-- outer-join
SELECT 	E.DEPTNO,D.DNAME,E.ENAME 
FROM    SCOTT.EMP E LEFT OUTER JOIN SCOTT.DEPT D
ON 		E.DEPTNO = D.DEPTNO
ORDER   BY E.DEPTNO;

SELECT 	E.DEPTNO,D.DNAME,E.ENAME 
FROM    SCOTT.EMP E RIGHT OUTER JOIN SCOTT.DEPT D
ON   	E.DEPTNO = D.DEPTNO
ORDER    BY E.DEPTNO;

SELECT 	D.DEPTNO,D.DNAME,E.ENAME 
FROM	SCOTT.EMP E RIGHT OUTER JOIN SCOTT.DEPT D
ON      E.DEPTNO = D.DEPTNO
ORDER    BY E.DEPTNO;

SELECT 	D.DEPTNO,D.DNAME,E.ENAME 
FROM	SCOTT.EMP E FULL OUTER JOIN SCOTT.DEPT D
ON      E.DEPTNO = D.DEPTNO 
ORDER   BY E.DEPTNO;

-- SELF-JOIN
SELECT E.ENAME||' ''S    MANAGER IS '||M.ENAME
FROM   EMP E,EMP M
WHERE  E.MGR = M.EMPNO
ORDER BY M.ENAME; 

SELECT E.ENAME||' ''S    MANAGER IS '||NVL(M.ENAME, 'UNKNOWN')
FROM   EMP E,EMP M
WHERE    E.MGR = M.EMPNO(+)
ORDER BY M.ENAME; 

SELECT E.ENAME||' ''S    MANAGER IS '||NVL(M.ENAME, 'UNKNOWN')
FROM   EMP E LEFT OUTER JOIN EMP M
ON    E.MGR = M.EMPNO
ORDER BY M.ENAME;

SELECT * FROM EMP;

-- CARTESIAN PRODUCT
SELECT	ENAME,JOB,DNAME
FROM 	EMP, DEPT
ORDER   BY ENAME; 

SELECT * FROM DEPT;

SELECT 	ENAME,JOB,DNAME, SAL, DEPT.DEPTNO
FROM    EMP , DEPT 
WHERE 	EMP.SAL > 2000   and DEPT.DEPTNO IN (10,20)
ORDER   BY ENAME; 

SELECT 	ENAME,JOB,DNAME, SAL, DEPT.DEPTNO
FROM    EMP , DEPT 
WHERE 	EMP.SAL > 2000 OR DEPT.DEPTNO IN (10,20)
ORDER   BY ENAME;    

SELECT	E.ENAME, E.JOB,E.SAL,S.GRADE, S.LOSAL, DEPTNO    
FROM    EMP E, SALGRADE S
WHERE 	E.SAL < S.LOSAL AND E.DEPTNO IN (10,30)
ORDER 	BY E.ENAME;