SELECT*FROM DA13.EMP;
ALTER USER DA13 IDENTIFIED BY yellow94;
SHOW USER;
```
SELECT * FROM V$SESSION;

ALTER TABLE DEPT MODIFY DNAME VARCHAR(20);
DESC DEPT

-- INSERT
INSERT INTO DEPT VALUES(50,'연구소1','서울');
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(51,'연구소2','대전');
SELECT * FROM DEPT;

INSERT INTO DEPT VALUES('중부영업점','대구');
INSERT INTO DEPT(DNAME,LOC) VALUES('중부영업점','대구');

    -- INSERT, NULL
 INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(52, '북부영업점',NULL); 
 INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(53, '남부영업점','');
INSERT INTO DEPT(DEPTNO,DNAME) VALUES(54,'서부영업점');

SELECT DEPTNO,DNAME,NVL(LOC,'미지정지역') AS LOC FROM DEPT; 
COMMIT;

-- UPDATE
UPDATE DEPT SET DNAME = '중부연구소' WHERE DEPTNO = 50;
UPDATE DEPT SET DNAME = '북서부연구소', LOC='인천' WHERE DEPTNO = 51;
SELECT * FROM DEPT WHERE DEPTNO IN (50,51);
COMMIT;

ALTER TABLE DEPT MODIFY LOC VARCHAR(20);
DESC DEPT

UPDATE DEPT SET LOC='미개척지역';
SELECT * FROM DEPT;
ROLLBACK;
SELECT * FROM DEPT;

-- DELETE
DELETE FROM DEPT WHERE LOC IS NULL;
DELETE DEPT;
SELECT * FROM DEPT;
ROLLBACK;

-- DML SUBQUERY
INSERT INTO BONUS(ENAME,JOB,SAL,COMM)
SELECT ENAME,JOB,SAL,COMM FROM EMP;

SELECT * FROM BONUS;

ROLLBACK;

SELECT * FROM BONUS;

INSERT INTO BONUS(ENAME, JOB, SAL, COMM)
    SELECT ENAME, JOB, SAL, DECODE(DEPTNO, 10, SAL*0.3, 20, SAL*0.2) + NVL(COMM, 0)
    FROM EMP
    WHERE DEPTNO IN (10,20);

SELECT * FROM BONUS;
COMMIT;
ROLLBACK;

UPDATE EMP SET COMM = (SELECT AVG(COMM)/2 FROM EMP)
WHERE COMM IS NULL OR COMM = 0;

SELECT * FROM EMP;
COMMIT;

DELETE FROM BONUS WHERE SAL > (SELECT AVG(SAL) FROM EMP);
SELECT * FROM BONUS;
COMMIT;

-- TRANSACTION
    -- TRANSACTION 시작과 종료
ROLLBACK;
INSERT INTO DEPT(DEPTNO, DNAME, LOC) VALUES(90, '신규사업부', '경기도');
UPDATE EMP SET DEPTNO = 90 WHERE DEPTNO = 30;
DELETE FROM DEPT WHERE DEPTNO = 30;
SELECT * FROM DEPT;
SELECT * FROM EMP WHERE DEPTNO = 30;
ROLLBACK;
SELECT * FROM DEPT;
SELECT * FROM EMP WHERE DEPTNO = 30;

    -- TRANSACTION 종료후 ROLLBACK 처리범위
INSERT INTO EMP(EMPNO,ENAME,JOB,SAL) VALUES(1111,'오라클','DBA',3500); 
UPDATE EMP SET SAL = SAL* 1.3;
COMMIT;
ROLLBACK WORK;
SELECT * FROM EMP;

    -- TRANSACTION과 DDL
INSERT INTO EMP(EMPNO,ENAME,DEPTNO) VALUES(9999,'OCPOK',20);
ALTER TABLE EMP ADD( SEX CHAR(1) DEFAULT 'M');
ROLLBACK;
DESC EMP;
ALTER TABLE EMP DROP COLUMN SEX;
ROLLBACK;
DESC EMP
ALTER TABLE EMP DROP COLUMN SEX;
ROLLBACK;
DESC EMP

-- ROLLBACK LEVEL
SELECT * FROM DEPT;
DESC EMP
ROLLBACK;
SELECT /* before transaction */ EMPNO, SAL FROM EMP WHERE EMPNO IN (7788, 7902);
DELETE FROM EMP WHERE DEPTNO = 10;
UPDATE /* STATEMENT LEVEL ROLLBACK*/ EMP SET SAL = 123456789 WHERE EMPNO = 7788;
UPDATE EMP SET SAL = 1234 WHERE EMPNO = 7902;
COMMIT;
    -- 데이터 확인
    SELECT /* After Transaction */ EMPNO, SAL FROM EMP WHERE EMPNO IN (7788, 7902);
    SELECT /* After Transaction */ EMPNO, SAL FROM EMP WHERE EMPNO = 10;
/*
BEGIN
    DELETE FROM EMP WHERE DEPTNO = 20;
    -- 자리수 초과 에러 발생
    UPDATE EMP SET SAL = 123456789 WHERE EMPNO = 7499;
    UPDATE EMP SET SAL = 1234 WHERE EMPNO = 7698;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
END;
*/

SELECT * FROM EMP;
SELECT /*After Transaction*/ EMPNO, SAL FROM EMP WHERE DEPTNO = 20;
SELECT /*After Transaction*/ EMPNO, SAL FROM EMP WHERE EMPNO IN (7499, 7698);