-- SINGLE COLUMN, SINGLE ROW
SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH');

SELECT ENAME, SAL FROM EMP WHERE SAL < (SELECT AVG(SAL) FROM EMP);

SELECT DEPTNO, ENAME, JOB, SAL,
    (SELECT ROUND(AVG(SAL), 0) FROM EMP S WHERE S.JOB = M.JOB)
    AS JOB_AVG_SAL
FROM EMP M
ORDER BY JOB;

SELECT *
FROM (SELECT EMPNO, ENAME, SAL
      FROM EMP
    ORDER BY SAL ASC)
WHERE ROWNUM <= 5;

SELECT DEPTNO, ENAME, EMP.JOB, SAL, IV.AVG_SAL
FROM EMP, (SELECT JOB, ROUND(AVG(SAL)) AS AVG_SAL FROM EMP
           GROUP BY JOB)IV
WHERE EMP.JOB = IV.JOB AND SAL > IV.AVG_SAL
ORDER BY DEPTNO, SAL DESC;

SELECT ENAME, SAL
FROM EMP WHERE SAL < (SELECT AVG(SAL) FROM EMP);

SELECT ROUND(AVG(SAL)) FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT JOB, ROUND(AVG(SAL)) AS AVG_SAL FROM EMP
           GROUP BY JOB;
           
SELECT DNAME, LOC FROM DEPT
WHERE DEPTNO = (SELECT DEPTNO FROM EMP
GROUP BY DEPTNO HAVING COUNT(*) > 3);

SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH');

SELECT DEPTNO, JOB FROM EMP
WHERE (DEPTNO, JOB) IN (SELECT DEPTNO, JOB FROM EMP
GROUP BY DEPTNO, JOB HAVING AVG(SAL) > 2000);

SELECT DEPTNO, JOB FROM EMP
GROUP BY DEPTNO, JOB HAVING AVG(SAL) > 2000;

SELECT DEPTNO, JOB, ENAME, SAL FROM EMP
WHERE SAL > 2000;