-- TRANSACTION과 읽기일관성 (READ CONSISTENCY)
    -- SESSION 2
/*(2)*/
SELECT DEPTNO, ENAME, SAL FROM EMP 
WHERE DEPTNO = 20;

/*(5) 위 쿼리 재실행 */

-- TRANSACTION과 ROW LEVEL LOCK
/*(2)*/
DELETE FROM EMP WHERE DEPTNO = 20;
/*(3)*/
DELETE FROM EMP WHERE DEPTNO = 10;

/*(5)*/
ROLLBACK;

-- SELECT * FOR UPDATE (ROW LEVEL LOCK)
-- (1)
DELETE FROM EMP WHERE DEPTNO = 20;
DELETE FROM EMP WHERE DEPTNO = 10;
ROLLBACK;

-- (2)
DELETE FROM EMP WHERE DEPTNO = 10;
ROLLBACK;

-- (3)
DELETE FROM EMP WHERE DEPTNO = 10;
ROLLBACK;