DESC CUSTOMER

SELECT CREDIT_LIMIT, SUBSTR(ADDRESS1, 1, 2) AS REGION, GENDER
FROM CUSTOMER 
WHERE ROWNUM <= 1000;

SELECT ADDRESS1
FROM CUSTOMER
WHERE SUBSTR(ADDRESS1, 1, 2) = 'uC';

SELECT SUBSTR(ADDRESS, 1, 2) AS REGION, GENDER, CREDIT_LIMIT
FROM (SELECT GENDER, CREDIT_LIMIT, REPLACE(SUBSTR(ADDRESS1, 1, 5), 'uC778', '인천') AS ADDRESS
      FROM CUSTOMER)
WHERE ROWNUM <= 1000;

SELECT GENDER
FROM CUSTOMER
GROUP BY GENDER;

SELECT BIRTH_DT, 2020 - EXTRACT(YEAR FROM BIRTH_DT) AS AGE
FROM CUSTOMER
WHERE ROWNUM <= 10;

-- 가공한 고객 데이터 
SELECT SUBSTR(ADDRESS, 1, 2) AS REGION, AGE, GENDER, CREDIT_LIMIT
FROM (SELECT GENDER, 2020 - EXTRACT(YEAR FROM BIRTH_DT) AS AGE, 
             CREDIT_LIMIT, REPLACE(SUBSTR(ADDRESS1, 1, 5), 'uC778', '인천') AS ADDRESS
      FROM CUSTOMER)
WHERE ROWNUM <= 1000;


SELECT CREDIT_LIMIT
FROM CUSTOMER
WHERE CREDIT_LIMIT IS NULL;

-- emp 테이블과 조인 
    -- 부서별, 매니저별 실적 
SELECT DEPTNO, ACCOUNT_MGR, count(*)
FROM CUSTOMER, EMP
WHERE EMP.EMPNO = CUSTOMER.ACCOUNT_MGR
GROUP BY DEPTNO, ACCOUNT_MGR
ORDER BY DEPTNO;

    -- 부서별 실적 
SELECT D.DNAME, COUNT(*) AS RESULT
FROM CUSTOMER C, EMP E, DEPT D
WHERE E.EMPNO = C.ACCOUNT_MGR AND E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME
ORDER BY D.DNAME;

select * from dept;
SELECT A.ENAME, 
    SUM(DECODE(A.AGE,20,1)) AS AGE_20, 
    SUM(DECODE(A.AGE,30,1)) AS AGE_30,  
    SUM(DECODE(A.AGE,40,1)) AS AGE_40, 
    SUM(DECODE(A.AGE,50,1)) AS AGE_50, 
    SUM(DECODE(A.AGE,60,1)) AS AGE_60  
FROM (SELECT C.ACCOUNT_MGR AS EMPNO, E.ENAME,  
            TRUNC(TO_CHAR(SYSDATE,'YYYY')-TO_CHAR(C.BIRTH_DT,'YYYY'),-1) AS AGE
      FROM CUSTOMER C, EMP E
      WHERE C.ACCOUNT_MGR  = E.EMPNO AND E.DEPTNO = 30) A  
GROUP BY A.ENAME;

-- 자바 
-- 성별 카드한도 평균
SELECT GENDER, ROUND(AVG(CREDIT_LIMIT)) AS AVERAGE_CREDIT_LIMIT
FROM CUSTOMER
GROUP BY GENDER;

-- 지역별 카드한도 평균
SELECT SUBSTR(ADDRESS, 1, 2) AS REGION, ROUND(AVG(CREDIT_LIMIT)) AS CREDIT_LIMIT_BY_REGION
FROM (SELECT GENDER, 2020 - EXTRACT(YEAR FROM BIRTH_DT) AS AGE, 
             CREDIT_LIMIT, REPLACE(SUBSTR(ADDRESS1, 1, 5), 'uC778', '인천') AS ADDRESS
      FROM CUSTOMER)
GROUP BY SUBSTR(ADDRESS, 1, 2)
ORDER BY REGION;

-- 세대별 카드한도 평균
SELECT GENERATION, ROUND(AVG(CREDIT_LIMIT), 0) AS CREDIT_LIMIT_BY_GEN
FROM CUSTOMER, (SELECT 
                    CASE WHEN 2020-EXTRACT(YEAR FROM BIRTH_DT) < 20 THEN '10대'
                         WHEN 2020-EXTRACT(YEAR FROM BIRTH_DT) < 30 THEN '20대'
                         WHEN 2020-EXTRACT(YEAR FROM BIRTH_DT) < 40 THEN '30대'
                         WHEN 2020-EXTRACT(YEAR FROM BIRTH_DT) < 50 THEN '40대'
                         WHEN 2020-EXTRACT(YEAR FROM BIRTH_DT) < 60 THEN '50대'
                         WHEN 2020-EXTRACT(YEAR FROM BIRTH_DT) > 60 THEN '60대 이상'
                         ELSE 'UNKNOWN'
                    END AS GENERATION
      FROM CUSTOMER)
WHERE ROWNUM <= 10000
GROUP BY GENERATION
ORDER BY GENERATION;
      
      
SELECT * FROM CUSTOMER WHERE ROWNUM <= 5;

SELECT SUBSTR(ADDRESS, 1, 2), COUNT(*)
FROM (SELECT REPLACE(SUBSTR(ADDRESS1, 1, 5), 'uC778', '인천') AS ADDRESS
      FROM CUSTOMER)
GROUP BY SUBSTR(ADDRESS, 1, 2);