-- DATA TYPE
    -- 테이블 생성
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    ID      VARCHAR2(8),
    PWD     CHAR(8),
    SEX     CHAR(1)
);

SELECT * FROM TAB;
DESC CUSTOMER

INSERT INTO CUSTOMER VALUES('XMAN', 'XMAN', 'M');
INSERT INTO CUSTOMER(ID, PWD, SEX) VALUES('ORACLE', 'OCM', 'F');
COMMIT;

INSERT INTO CUSTOMER(ID, PWD, SEX) VALUES('NULL1', 'ZMAN', NULL);
INSERT INTO CUSTOMER(ID, PWD, SEX) VALUES('NULL2', 'YMAN', '');
INSERT INTO CUSTOMER(ID, PWD) VALUES('NULL3', 'LMAN');

    -- 고정길이와 가변길이의 차이점 비교
SELECT ID, LENGTH(ID), VSIZE(ID), PWD, LENGTH(PWD), VSIZE(PWD) FROM CUSTOMER;
SELECT ID, REPLACE(ID, ' ', '?'), PWD, REPLACE(PWD, ' ', '?') FROM CUSTOMER;
 
    -- VARCHAR
SELECT * FROM CUSTOMER WHERE ID = 'XMAN ';
SELECT * FROM CUSTOMER WHERE ID = PWD;
SELECT * FROM CUSTOMER WHERE ID = SUBSTR('XMAN', 1, 2) || SUBSTR('XMAN', 3, 2);

    -- CHAR
SELECT * FROM CUSTOMER WHERE PWD = 'XMAN ';
SELECT * FROM CUSTOMER WHERE PWD = SUBSTR('XMAN', 1, 2) || SUBSTR('XMAN', 3, 2);
SELECT * FROM CUSTOMER WHERE PWD LIKE SUBSTR('XMAN', 1, 2) || SUBSTR('XMAN', 3, 2) || '%';

SELECT * FROM CUSTOMER;

-- 테이블 생성(숫자 DATA TYPE)
DROP   TABLE  TST_NUMBER;
CREATE TABLE  TST_NUMBER(
    NUM     NUMBER,
    AGE     NUMBER(3)  DEFAULT 18,
    TAX     NUMBER(7,2)
);
INSERT INTO TST_NUMBER  VALUES(123.5,123.5,123.5);
INSERT INTO TST_NUMBER  VALUES(123,  123,123);
INSERT INTO TST_NUMBER  VALUES(123,  12345,123);
INSERT INTO TST_NUMBER  VALUES(123,  123,123.56789);
INSERT INTO TST_NUMBER  VALUES(123,  '123',123.56789);
INSERT INTO TST_NUMBER(NUM, TAX)   VALUES(456,456);
SELECT  * FROM TST_NUMBER;

-- 날짜 DATE TYPE
    -- DEFAULT에 TO_CHAR(SYSDATE, 'YY/MM/DD')를 사용할 수 있는지를 확인하는 SQL 작성
    
DROP   TABLE TST_DATE;

CREATE TABLE TST_DATE(
    CHAR_HIREDATE   VARCHAR2(8),
    DATE_HIREDATE   DATE,
    LOG_DATE        DATE    DEFAULT SYSDATE);
    
INSERT INTO TST_DATE(CHAR_HIREDATE, DATE_HIREDATE) 
VALUES(TO_CHAR(SYSDATE, 'YYYYMMDD'), SYSDATE);

INSERT INTO TST_DATE(CHAR_HIREDATE, DATE_HIREDATE) 
VALUES('19990921', TO_DATE('990921', 'YYMMDD'));

SELECT * FROM TST_DATE;

-- ALTER
ALTER TABLE TST_DATE ADD(
    NAME    VARCHAR2(20),
    AGE     NUMBER(3)
);
DESC TST_DATE

ALTER TABLE TST_DATE DROP COLUMN AGE;
DESC TST_DATE

-- DROP
SELECT * FROM TAB;

DROP TABLE TST_DATE;

DESC TST_DATE
SELECT * FROM TAB;

-- SUBQUERY에 의한 TABLE 생성
DROP TABLE EMP_CTAS;
CREATE TABLE EMP_CTAS AS SELECT * FROM EMP;

DESC EMP_CTAS
SELECT * FROM EMP_CTAS;

DROP TABLE EMP_CTAS_J;

CREATE TABLE EMP_CTAS_J
AS SELECT EMPNO, ENAME, DEPT.DNAME, SAL * 12 AS ANNUAL_SAL
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.DEPTNO IN (10, 20);

DESC EMP_CTAS_J
SELECT * FROM EMP_CTAS_J;


