SELECT * FROM SYSTEM13;
SELECT * FROM RESOURCE_USAGE13;

-- 과제 2번
    -- MAX는 그룹행함수,
    -- 문자는 ASCII 코드로 비교되므로 "사"용이 "미"사용보다 더 높아서 사용이 된다.
SELECT S.SYSTEM_ID,S.SYSTEM_NAME,
       MAX(DECODE(R.RESOURCE_NAME, 'FTP', '사용', '미사용')) AS "FTP",
       MAX(DECODE(R.RESOURCE_NAME, 'TELNET', '사용', '미사용')) AS "TELNET",
       MAX(DECODE(R.RESOURCE_NAME, 'EMAIL', '사용', '미사용')) AS "EMAIL"
FROM SYSTEM13 S, RESOURCE_USAGE13 R
WHERE S.SYSTEM_ID = R.SYSTEM_ID(+)
GROUP BY S.SYSTEM_ID, S.SYSTEM_NAME
ORDER BY S.SYSTEM_ID;

