SELECT * FROM SYSTEM13;
SELECT * FROM RESOURCE_USAGE13;

-- 과제 2번
    -- MAX는 그룹행함수,
    -- 문자는 ASCII 코드로 비교되므로 "사"용이 "미"사용보다 더 높아서 사용이 된다.
SELECT S.SYSTEM_ID,S.SYSTEM_NAME,
       MAX(DECODE(R.RESOURCE_NAME, 'FTP', '사용', '미사용')) AS "FTP",
       MAX(DECODE(R.RESOURCE_NAME, 'TELNET', '사용', '미사용')) AS "TELNET",
       MAX(DECODE(R.RESOURCE_NAME, 'EMAIL', '사용', '미사용')) AS "EMAIL"
FROM SYSTEM13 S, RESOURCE_USAGE13 R
WHERE S.SYSTEM_ID = R.SYSTEM_ID(+)
GROUP BY S.SYSTEM_ID, S.SYSTEM_NAME
ORDER BY S.SYSTEM_ID;

-- 과제 3번
    -- 까막
SELECT A.DEPTNO AS 부서번호, A.ENAME AS 이름, A.JOB AS 직업, A.SAL AS 급여,
COUNT(DISTINCT B.SAL) AS "급여순위"
FROM EMP A, EMP B 
WHERE A.DEPTNO = B.DEPTNO
AND
A.SAL <= B.SAL 
GROUP BY A.DEPTNO, A.ENAME, A.JOB, A.SAL
ORDER BY A.DEPTNO ASC, A.SAL DESC;
    -- 나
SELECT  A.DEPTNO AS 부서번호, A.ENAME AS 이름, A.JOB AS 직업, A.SAL AS 급여, COUNT(B.ENAME) + 1 AS "급여순위"
FROM EMP A, EMP B
WHERE A.SAL < B.SAL(+) 
AND A.DEPTNO = B.DEPTNO(+)
GROUP BY A.DEPTNO, A.ENAME, A.JOB, A.SAL
ORDER BY A.DEPTNO, A.SAL DESC;

-- 과제 4번
    -- RANK()
SELECT DEPTNO AS 부서번호, ENAME AS 이름, JOB AS 직업, SAL AS 급여, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS "급여순위"
FROM EMP 
GROUP BY DEPTNO, JOB, ENAME, SAL;

    -- DENSE_RANK()
SELECT DEPTNO AS 부서번호, ENAME AS 이름, JOB AS 직업, SAL AS 급여, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS "급여순위"
FROM EMP 
GROUP BY DEPTNO, JOB, ENAME, SAL;

-- 과제 5번
SELECT DEPTNO, EMPNO, ENAME, SAL, TRUNC(SAL/SUM_SAL*100, 2) AS SAL_RATE
FROM EMP, (SELECT SUM(SAL) AS SUM_SAL FROM EMP);

SELECT*FROM EMP;