CREATE TABLE SYSTEM13(SYSTEM_ID   VARCHAR2(5),
                      SYSTEM_NAME VARCHAR2(11)
);

INSERT INTO SYSTEM13 VALUES('XXX', '혜화DB');
INSERT INTO SYSTEM13 VALUES('YYY', '강남DB');
INSERT INTO SYSTEM13 VALUES('ZZZ', '영등포DB');

DROP TABLE RESOURCE_USAGE13;

CREATE TABLE RESOURCE_USAGE13(SYSTEM_ID       VARCHAR2(5),
                            RESOURCE_NAME     VARCHAR2(10)
);

INSERT INTO RESOURCE_USAGE13 VALUES('XXX', 'FTP');
INSERT INTO RESOURCE_USAGE13 VALUES('YYY', 'FTP');
INSERT INTO RESOURCE_USAGE13 VALUES('YYY', 'TELNET');
INSERT INTO RESOURCE_USAGE13 VALUES('YYY', 'EMAIL');
COMMIT;

 